#!/bin/bash --login
#
#PBS -l select=4:ncpus=36
#PBS -l place=excl
#PBS -N ParapoxyVirus-B159973
#PBS -A d171-s1667002
#PBS -l walltime=0:14:0

# Switch to current working directory
cd $PBS_O_WORKDIR

# Load modules
module load mpt
#If you want you can include the latest MPI Intel
# module load intel-mpi-17

# Run the parallel program on four different nodes for four processes.
mpiexec_mpt -ppn 1 -n 4 .bin/parapoxvirus > months.out



